version: "3.8"

services:
  stub-bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    # монтируем код на время разработки, можно убрать в проде
    volumes:
      - .:/app
    # подтягиваем сразу всё из .env
    env_file:
      - .env
    # (опционально) чтобы явно видеть, какие переменные мы используем
    environment:
      - API_TOKEN
      - SUB_CHANNEL_USERNAME
      - ADMIN_CHANNEL_USERNAME
      - ADMIN_IDS
    command: python stub_bot.py
    restart: unless-stopped
