services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - shared_tmp:/shared_tmp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: python bot.py
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - shared_tmp:/shared_tmp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A celery_app worker --concurrency=16 --loglevel=info
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - shared_tmp:/shared_tmp
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    restart: unless-stopped

#  stub-bot:
#   build:
#      context: .
#      dockerfile: Dockerfile
#    working_dir: /app
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    environment:
#      - STUB_BOT_TOKEN
#    command: python stub_bot.py
#    restart: unless-stopped

volumes:
  shared_tmp: